### ISSUE TITLE
Possible to check deposits

### ISSUE THREAD

**Issue by ivanperez-keera** [bankscrap/bankscrap-ing#6]
Hi. I used this and didn't get any info on deposits.

Is that info, in principle, available? Could it be implemented?

**Comment by javiercr** [comment]
Same thing than with https://github.com/bankscrap/bankscrap-bbva/issues/4. @raulmarcosl do you have any deposit on ING?

@ivanperez-keera by the way, did you test this adapter with a ING bank account from some country other than Spain? So far we only tested it with Spanish accounts so it would be nice to confirm it works with other countries.

**Comment by ivanperez-keera** [comment]
I have not tested the ING adapter with accounts in countries other than Spain, no.

I have a deposit. If this is implemented, I can test it.
